[package]
name = "getup"
version = "0.1.0"
authors = ["Abhilash Raj <raj.abhilash1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.13.0"
