unstable_features = true
edition = "2018"

imports_layout = "HorizontalVertical"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
max_width = 89
comment_width = 89
use_small_heuristics = "max"
